In [1]:
#Q1
import numpy as np

In [12]:
a = np.arange(25).reshape(5, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [14]:
print(a[1][2])

7


In [22]:
a[a%2!=0]=-1


In [24]:
a

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1],
       [10, -1, 12, -1, 14],
       [-1, 16, -1, 18, -1],
       [20, -1, 22, -1, 24]])

In [1]:
#Q2
import numpy as np

array = np.random.randint(10, 51, size=(2, 3, 4))
print("Original Array:\n", array)

sliced = array[:, :, -2:]
print("\nSliced (last 2 elements from each inner-most array):\n", sliced)

subtracted = array - 10
print("\nArray after subtracting 10:\n", subtracted)


Original Array:
 [[[32 26 45 47]
  [47 36 15 22]
  [34 39 19 26]]

 [[44 33 21 49]
  [39 37 30 42]
  [34 14 27 30]]]

Sliced (last 2 elements from each inner-most array):
 [[[45 47]
  [15 22]
  [19 26]]

 [[21 49]
  [30 42]
  [27 30]]]

Array after subtracting 10:
 [[[22 16 35 37]
  [37 26  5 12]
  [24 29  9 16]]

 [[34 23 11 39]
  [29 27 20 32]
  [24  4 17 20]]]


In [2]:
import pandas as pd

marks = [65, 70, 85, 90, 55]
student_names = ['Virat', 'Gayle', 'Dravid', 'Hazelwood', 'Dhoni']
student_series = pd.Series(marks, index=student_names)

average_marks = student_series.mean()
students_above_75 = student_series[student_series > 75]

print(student_series)
print("\nAverage Marks:", average_marks)
print("\nStudents who scored more than 75:\n", students_above_75)


Virat        65
Gayle        70
Dravid       85
Hazelwood    90
Dhoni        55
dtype: int64

Average Marks: 73.0

Students who scored more than 75:
 Dravid       85
Hazelwood    90
dtype: int64


In [3]:
import pandas as pd

data = {
    'EmpID': [111, 222, 333, 444, 555],
    'Name': ['Shilpa', 'Pushpa', 'Rajani', 'Dhanush', 'Shashank'],
    'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales'],
    'Salary': [50000, 60000, 55000, 70000, 45000]
}

df = pd.DataFrame(data)

data_types = df.dtypes
df['Bonus'] = df['Salary'] * 0.10

print(df)
print("\nData Types:\n", data_types)


   EmpID      Name Department  Salary   Bonus
0    111    Shilpa         HR   50000  5000.0
1    222    Pushpa         IT   60000  6000.0
2    333    Rajani    Finance   55000  5500.0
3    444   Dhanush  Marketing   70000  7000.0
4    555  Shashank      Sales   45000  4500.0

Data Types:
 EmpID          int64
Name          object
Department    object
Salary         int64
dtype: object
